/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BindingForm.java
 *
 * Created on Dec 3, 2011, 1:29:05 PM
 */
package latticetestwork;

/**
 *
 * @author mewer12
 */
public class BindingForm extends javax.swing.JFrame {

    public LatticeTestworkView parent = null;
    
    /** Creates new form BindingForm */
    public BindingForm(LatticeTestworkView parent) {
        this.parent = parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioBindNSphere = new javax.swing.JRadioButton();
        radioBindNCube = new javax.swing.JRadioButton();
        radioBindSkeletonShell = new javax.swing.JRadioButton();
        radioBindInNSphere = new javax.swing.JRadioButton();
        radioBindInNCube = new javax.swing.JRadioButton();
        radioBindSkeletonSkin = new javax.swing.JRadioButton();
        radioBindFunction = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaBindingFunction = new javax.swing.JTextArea();
        btnBind = new javax.swing.JButton();
        btnBind10 = new javax.swing.JButton();
        btnBind100 = new javax.swing.JButton();
        btnBind1000 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        boxRepel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(latticetestwork.LatticeTestworkApp.class).getContext().getResourceMap(BindingForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        buttonGroup1.add(radioBindNSphere);
        radioBindNSphere.setSelected(true);
        radioBindNSphere.setText(resourceMap.getString("radioBindNSphere.text")); // NOI18N
        radioBindNSphere.setName("radioBindNSphere"); // NOI18N

        buttonGroup1.add(radioBindNCube);
        radioBindNCube.setText(resourceMap.getString("radioBindNCube.text")); // NOI18N
        radioBindNCube.setName("radioBindNCube"); // NOI18N

        buttonGroup1.add(radioBindSkeletonShell);
        radioBindSkeletonShell.setText(resourceMap.getString("radioBindSkeletonShell.text")); // NOI18N
        radioBindSkeletonShell.setName("radioBindSkeletonShell"); // NOI18N

        buttonGroup1.add(radioBindInNSphere);
        radioBindInNSphere.setText(resourceMap.getString("radioBindInNSphere.text")); // NOI18N
        radioBindInNSphere.setName("radioBindInNSphere"); // NOI18N

        buttonGroup1.add(radioBindInNCube);
        radioBindInNCube.setText(resourceMap.getString("radioBindInNCube.text")); // NOI18N
        radioBindInNCube.setName("radioBindInNCube"); // NOI18N

        buttonGroup1.add(radioBindSkeletonSkin);
        radioBindSkeletonSkin.setText(resourceMap.getString("radioBindSkeletonSkin.text")); // NOI18N
        radioBindSkeletonSkin.setName("radioBindSkeletonSkin"); // NOI18N

        buttonGroup1.add(radioBindFunction);
        radioBindFunction.setText(resourceMap.getString("radioBindFunction.text")); // NOI18N
        radioBindFunction.setToolTipText(resourceMap.getString("radioBindFunction.toolTipText")); // NOI18N
        radioBindFunction.setName("radioBindFunction"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        areaBindingFunction.setColumns(20);
        areaBindingFunction.setRows(5);
        areaBindingFunction.setName("areaBindingFunction"); // NOI18N
        jScrollPane1.setViewportView(areaBindingFunction);

        btnBind.setText(resourceMap.getString("btnBind.text")); // NOI18N
        btnBind.setName("btnBind"); // NOI18N

        btnBind10.setText(resourceMap.getString("btnBind10.text")); // NOI18N
        btnBind10.setName("btnBind10"); // NOI18N

        btnBind100.setText(resourceMap.getString("btnBind100.text")); // NOI18N
        btnBind100.setName("btnBind100"); // NOI18N

        btnBind1000.setText(resourceMap.getString("btnBind1000.text")); // NOI18N
        btnBind1000.setName("btnBind1000"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        boxRepel.setSelected(true);
        boxRepel.setText(resourceMap.getString("boxRepel.text")); // NOI18N
        boxRepel.setName("boxRepel"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindNSphere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBind))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindNCube)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(btnBind100))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindSkeletonShell)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                .addComponent(boxRepel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindInNSphere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addComponent(btnBind10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindInNCube)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(btnBind1000))
                            .addComponent(radioBindSkeletonSkin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBindFunction)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindNSphere)
                    .addComponent(btnBind)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindInNSphere)
                    .addComponent(btnBind10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindNCube)
                    .addComponent(btnBind100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindInNCube)
                    .addComponent(btnBind1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindSkeletonShell)
                    .addComponent(boxRepel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBindSkeletonSkin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBindFunction)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(100, 100, 410, 408);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BindingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BindingForm(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaBindingFunction;
    private javax.swing.JCheckBox boxRepel;
    private javax.swing.JButton btnBind;
    private javax.swing.JButton btnBind10;
    private javax.swing.JButton btnBind100;
    private javax.swing.JButton btnBind1000;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radioBindFunction;
    private javax.swing.JRadioButton radioBindInNCube;
    private javax.swing.JRadioButton radioBindInNSphere;
    private javax.swing.JRadioButton radioBindNCube;
    private javax.swing.JRadioButton radioBindNSphere;
    private javax.swing.JRadioButton radioBindSkeletonShell;
    private javax.swing.JRadioButton radioBindSkeletonSkin;
    // End of variables declaration//GEN-END:variables
}
