/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphForm.java
 *
 * Created on Mar 12, 2013, 1:41:13 PM
 */
package latticetestwork;

import java.awt.Color;
import latticetestwork.Engine.Stick;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.statistics.HistogramDataset;

/**
 *
 * @author erhannis
 */
public class GraphForm extends javax.swing.JFrame {

    public LatticeTestworkView parent = null;
    public JFreeChart chart = null;
    public GraphDisplayPanel dp = null;

    /** Creates new form GraphForm */
    public GraphForm(LatticeTestworkView parent) {
        this.parent = parent;
        initComponents();

        this.dp = new GraphDisplayPanel(this);
        this.jSplitPane1.setRightComponent(dp);
        //testSetPenguinGraph();
    }

    public void testSetPenguinGraph() {
        HistogramDataset data = new HistogramDataset();
        double[] dataCumulative = new double[]{};
        double[] data1 = new double[]{1, 1.1, 1.3, 2};
        double[] data2 = (double[])MeUtils.randomDArray(Engine.r, 10);
        dataCumulative = (double[])MeUtils.concatArrays(dataCumulative, data1);
        data.addSeries(1, dataCumulative, 5);
        dataCumulative = (double[])MeUtils.concatArrays(dataCumulative, data2);
        data.addSeries(2, dataCumulative, 5);
        StandardChartTheme sct = new StandardChartTheme("Standard Chart Theme - Mod");
        sct.setXYBarPainter(new StandardXYBarPainter());        
        ChartFactory.setChartTheme(sct);
        chart = ChartFactory.createHistogram("A Fine Histogram", "Fish Consumed", "# Of Penguins", data, PlotOrientation.VERTICAL, false, false, false);
        ((XYBarRenderer)((XYPlot)chart.getPlot()).getRenderer()).setDrawBarOutline(true);
        ((XYPlot)chart.getPlot()).getRenderer().setOutlinePaint(new Color(0x000000));
        //((XYBarRenderer)((XYPlot)chart.getPlot()).getRenderer())
        
        dp.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnGraphEdgeLengths = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("latticetestwork/resources/GraphForm"); // NOI18N
        setTitle(bundle.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        btnGraphEdgeLengths.setText(bundle.getString("btnGraphEdgeLengths.text")); // NOI18N
        btnGraphEdgeLengths.setName("btnGraphEdgeLengths"); // NOI18N
        btnGraphEdgeLengths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphEdgeLengthsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGraphEdgeLengths)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGraphEdgeLengths)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnGraphEdgeLengthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphEdgeLengthsActionPerformed
    if (parent.engine != null && parent.engine.lattice != null) {
        if (parent.engine.sticksChanged) {
            parent.engine.updateSticks();
        }
        double[] lengths = new double[parent.engine.completeSticks.size() + parent.engine.incompleteSticks.size()];
        
        int i = 0;
        for (Stick s : parent.engine.completeSticks) {
            lengths[i++] = s.pointA.dist(s.pointB);
        }
        for (Stick s : parent.engine.incompleteSticks) {
            lengths[i++] = s.pointA.dist(s.pointB);
        }
        
        HistogramDataset data = new HistogramDataset();
        data.addSeries(1, lengths, 50);
        StandardChartTheme sct = new StandardChartTheme("Standard Chart Theme - Mod");
        sct.setXYBarPainter(new StandardXYBarPainter());        
        ChartFactory.setChartTheme(sct);
        chart = ChartFactory.createHistogram("Edge Lengths", "Lengths", "Count", data, PlotOrientation.VERTICAL, false, false, false);
        ((XYBarRenderer)((XYPlot)chart.getPlot()).getRenderer()).setDrawBarOutline(true);
        ((XYPlot)chart.getPlot()).getRenderer().setOutlinePaint(new Color(0x000000));
        //((XYBarRenderer)((XYPlot)chart.getPlot()).getRenderer())
        
        dp.repaint();
    }
}//GEN-LAST:event_btnGraphEdgeLengthsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GraphForm(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraphEdgeLengths;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
