/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphDisplayPanel.java
 *
 * Created on Mar 12, 2013, 1:43:20 PM
 */
package latticetestwork;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author erhannis
 */
public class GraphDisplayPanel extends javax.swing.JPanel {

    public GraphForm parent = null;
    
    /** Creates new form GraphDisplayPanel */
    public GraphDisplayPanel(GraphForm parent) {
        this.parent = parent;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g1) {
        super.paintComponent(g1);
        if (parent.chart != null) {
            Graphics2D g = (Graphics2D)g1;
            parent.chart.draw(g, this.getVisibleRect());
            //engine.render(g, 0, this.getWidth(), this.getHeight(), transX, transY, scaleX, scaleY, clickRender);
            //clickRender = false;
        }
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
