/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RepulsionForm.java
 *
 * Created on Dec 3, 2011, 1:45:51 PM
 */
package latticetestwork;

/**
 *
 * @author mewer12
 */
public class RepulsionForm extends javax.swing.JFrame {

    public LatticeTestworkView parent = null;
    
    /** Creates new form RepulsionForm */
    public RepulsionForm(LatticeTestworkView parent) {
        this.parent = parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRepulsionMode = new javax.swing.ButtonGroup();
        radioRepelCurrent = new javax.swing.JRadioButton();
        radioRepelStandard = new javax.swing.JRadioButton();
        radioRepelFunction = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        editRepulsionCutoff = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("latticetestwork/resources/RepulsionForm"); // NOI18N
        setTitle(bundle.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        groupRepulsionMode.add(radioRepelCurrent);
        radioRepelCurrent.setSelected(true);
        radioRepelCurrent.setText(bundle.getString("radioRepelCurrent.text")); // NOI18N
        radioRepelCurrent.setName("radioRepelCurrent"); // NOI18N

        groupRepulsionMode.add(radioRepelStandard);
        radioRepelStandard.setText(bundle.getString("radioRepelStandard.text")); // NOI18N
        radioRepelStandard.setName("radioRepelStandard"); // NOI18N

        groupRepulsionMode.add(radioRepelFunction);
        radioRepelFunction.setText(bundle.getString("radioRepelFunction.text")); // NOI18N
        radioRepelFunction.setName("radioRepelFunction"); // NOI18N

        jLabel1.setText(bundle.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        editRepulsionCutoff.setText(bundle.getString("editRepulsionCutoff.text")); // NOI18N
        editRepulsionCutoff.setName("editRepulsionCutoff"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRepelCurrent)
                    .addComponent(radioRepelStandard)
                    .addComponent(radioRepelFunction)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editRepulsionCutoff, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioRepelCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRepelStandard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioRepelFunction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editRepulsionCutoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setLocation(new java.awt.Point(75, 75));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepulsionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepulsionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepulsionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepulsionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RepulsionForm(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField editRepulsionCutoff;
    public javax.swing.ButtonGroup groupRepulsionMode;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton radioRepelCurrent;
    public javax.swing.JRadioButton radioRepelFunction;
    public javax.swing.JRadioButton radioRepelStandard;
    // End of variables declaration//GEN-END:variables
}
