/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotationForm.java
 *
 * Created on Nov 14, 2011, 10:33:48 PM
 */
package latticetestwork;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.GroupLayout.Group;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JScrollBar;
import latticetestwork.Engine.Stick;

/**
 *
 * @author mewer12
 */
public class RotationForm extends javax.swing.JFrame {

    public JScrollBar[] scrollBars;
    public int[][] coords;
    public LatticeTestworkView parent = null;
    public int dims = 0;
    public boolean resettingRotations = false;

    /** Creates new form RotationForm */
    public RotationForm(int dims, LatticeTestworkView parent) {
        this.dims = dims;
        this.parent = parent;

        initComponents();

        
        scrollBars = new JScrollBar[dims * (dims - 1) / 2];
        coords = new int[dims * (dims - 1) / 2][2];
        int index = 0;
        for (int i = 0; i < dims - 1; i++) {
            for (int j = i + 1; j < dims; j++) {
                coords[index][0] = i;
                coords[index][1] = j;
                scrollBars[index] = new JScrollBar();
                scrollBars[index].setMaximum(628);
                scrollBars[index].setMinimum(-628);
//            scrollBars[index].setOrientation(javax.swing.JScrollBar.HORIZONTAL);
                scrollBars[index].setName("scrollBar" + (i + 1) + "x" + (j + 1)); // NOI18N
                scrollBars[index].setToolTipText((i + 1) + "x" + (j + 1));
                scrollBars[index].addAdjustmentListener(new java.awt.event.AdjustmentListener() {

                    public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                        if (!resettingRotations) {
                            RotationForm.this.parent.rotate();
                        }
                    }
                });
                index++;
            }
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(layout);
        //getContentPane().setLayout(layout);
        SequentialGroup sg = layout.createSequentialGroup().addContainerGap();
        for (int i = 0; i < scrollBars.length - 1; i++) {
            sg = sg.addComponent(scrollBars[i], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        if (scrollBars.length > 0)
            sg = sg.addComponent(scrollBars[scrollBars.length - 1], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(356, Short.MAX_VALUE);
        ParallelGroup pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(sg);
        layout.setHorizontalGroup(pg);

        pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING);
        for (int i = 0; i < scrollBars.length; i++) {
            pg = pg.addComponent(scrollBars[i], javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE);
        }
        sg = layout.createSequentialGroup().addContainerGap().addGroup(pg).addContainerGap();
        Group vg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sg);
        layout.setVerticalGroup(vg);

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        boxHideImmune = new javax.swing.JCheckBox();
        btnRender = new javax.swing.JButton();
        boxHideComplete = new javax.swing.JCheckBox();
        btnZoomOut = new javax.swing.JButton();
        btnZoomIn = new javax.swing.JButton();
        barTransY = new javax.swing.JScrollBar();
        barTransX = new javax.swing.JScrollBar();
        boxHideIncomplete = new javax.swing.JCheckBox();
        boxHidePoints = new javax.swing.JCheckBox();
        btnRecalcSticks = new javax.swing.JButton();
        btnResetRotations = new javax.swing.JButton();
        btnPareSticks = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(latticetestwork.LatticeTestworkApp.class).getContext().getResourceMap(RotationForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        boxHideImmune.setText(resourceMap.getString("boxHideImmune.text")); // NOI18N
        boxHideImmune.setName("boxHideImmune"); // NOI18N
        boxHideImmune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHideImmuneActionPerformed(evt);
            }
        });

        btnRender.setText(resourceMap.getString("btnRender.text")); // NOI18N
        btnRender.setName("btnRender"); // NOI18N
        btnRender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenderActionPerformed(evt);
            }
        });

        boxHideComplete.setText(resourceMap.getString("boxHideComplete.text")); // NOI18N
        boxHideComplete.setName("boxHideComplete"); // NOI18N
        boxHideComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHideCompleteActionPerformed(evt);
            }
        });

        btnZoomOut.setText(resourceMap.getString("btnZoomOut.text")); // NOI18N
        btnZoomOut.setName("btnZoomOut"); // NOI18N
        btnZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomOutActionPerformed(evt);
            }
        });

        btnZoomIn.setText(resourceMap.getString("btnZoomIn.text")); // NOI18N
        btnZoomIn.setName("btnZoomIn"); // NOI18N
        btnZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomInActionPerformed(evt);
            }
        });

        barTransY.setMinimum(-100);
        barTransY.setName("barTransY"); // NOI18N
        barTransY.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barTransYAdjustmentValueChanged(evt);
            }
        });

        barTransX.setMinimum(-100);
        barTransX.setName("barTransX"); // NOI18N
        barTransX.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barTransXAdjustmentValueChanged(evt);
            }
        });

        boxHideIncomplete.setText(resourceMap.getString("boxHideIncomplete.text")); // NOI18N
        boxHideIncomplete.setName("boxHideIncomplete"); // NOI18N
        boxHideIncomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHideIncompleteActionPerformed(evt);
            }
        });

        boxHidePoints.setText(resourceMap.getString("boxHidePoints.text")); // NOI18N
        boxHidePoints.setName("boxHidePoints"); // NOI18N
        boxHidePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHidePointsActionPerformed(evt);
            }
        });

        btnRecalcSticks.setText(resourceMap.getString("btnRecalcSticks.text")); // NOI18N
        btnRecalcSticks.setName("btnRecalcSticks"); // NOI18N
        btnRecalcSticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecalcSticksActionPerformed(evt);
            }
        });

        btnResetRotations.setText(resourceMap.getString("btnResetRotations.text")); // NOI18N
        btnResetRotations.setName("btnResetRotations"); // NOI18N
        btnResetRotations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetRotationsActionPerformed(evt);
            }
        });

        btnPareSticks.setText(resourceMap.getString("btnPareSticks.text")); // NOI18N
        btnPareSticks.setName("btnPareSticks"); // NOI18N
        btnPareSticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPareSticksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnResetRotations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnZoomIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZoomOut, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxHideImmune)
                            .addComponent(boxHideComplete)
                            .addComponent(boxHideIncomplete)
                            .addComponent(boxHidePoints))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPareSticks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(barTransX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barTransY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRecalcSticks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(boxHideImmune)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxHideComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxHideIncomplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxHidePoints))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRender)
                            .addComponent(btnRecalcSticks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPareSticks)
                            .addComponent(barTransX, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(barTransY, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZoomIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZoomOut)
                    .addComponent(btnResetRotations))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        setBounds(50, 50, 463, 348);
    }// </editor-fold>//GEN-END:initComponents

private void boxHideImmuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHideImmuneActionPerformed
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_boxHideImmuneActionPerformed

private void btnRenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenderActionPerformed
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_btnRenderActionPerformed

private void boxHideCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHideCompleteActionPerformed
    if (parent.engine != null) {
        parent.engine.sticksChanged = true;
    }
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_boxHideCompleteActionPerformed

private void barTransXAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barTransXAdjustmentValueChanged
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_barTransXAdjustmentValueChanged

private void barTransYAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barTransYAdjustmentValueChanged
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_barTransYAdjustmentValueChanged

private void btnZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomInActionPerformed
    if (parent.engine != null) {
        parent.dp.scaleX *= 1.25;
        parent.dp.scaleY *= 1.25;
        parent.dp.repaint();
    }
}//GEN-LAST:event_btnZoomInActionPerformed

private void btnZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomOutActionPerformed
    if (parent.engine != null) {
        parent.dp.scaleX *= 0.75;
        parent.dp.scaleY *= 0.75;
        parent.dp.repaint();
    }
}//GEN-LAST:event_btnZoomOutActionPerformed

private void boxHideIncompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHideIncompleteActionPerformed
    if (parent.engine != null) {
        parent.engine.sticksChanged = true;
    }
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_boxHideIncompleteActionPerformed

private void boxHidePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHidePointsActionPerformed
    parent.updateOptions();
    parent.dp.repaint();
}//GEN-LAST:event_boxHidePointsActionPerformed

private void btnRecalcSticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecalcSticksActionPerformed
    if (parent.engine != null) {
        parent.updateOptions();
        parent.engine.updateSticks();
        parent.dp.repaint();
    }
}//GEN-LAST:event_btnRecalcSticksActionPerformed

private void btnResetRotationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRotationsActionPerformed
    if (parent.engine != null) {
        resettingRotations = true;
        for (int i = 0; i < scrollBars.length; i++) {
            scrollBars[i].setValue(0);
        }
        resettingRotations = false;
        parent.updateOptions();
        parent.dp.repaint();
    }
}//GEN-LAST:event_btnResetRotationsActionPerformed

private void btnPareSticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPareSticksActionPerformed
    if (parent.engine != null) {
        int i = 0;
        Iterator<Stick> it = parent.engine.completeSticks.iterator();
        while (it.hasNext()) {
            it.next();
            if (i % 2 == 0) {
                it.remove();
            }
            i++;
        }
        i = 0;
        it = parent.engine.incompleteSticks.iterator();
        while (it.hasNext()) {
            it.next();
            if (i % 2 == 0) {
                it.remove();
            }
            i++;
        }
        parent.dp.repaint();
    }
}//GEN-LAST:event_btnPareSticksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RotationForm(1, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollBar barTransX;
    public javax.swing.JScrollBar barTransY;
    public javax.swing.JCheckBox boxHideComplete;
    public javax.swing.JCheckBox boxHideImmune;
    public javax.swing.JCheckBox boxHideIncomplete;
    public javax.swing.JCheckBox boxHidePoints;
    private javax.swing.JButton btnPareSticks;
    private javax.swing.JButton btnRecalcSticks;
    private javax.swing.JButton btnRender;
    private javax.swing.JButton btnResetRotations;
    private javax.swing.JButton btnZoomIn;
    private javax.swing.JButton btnZoomOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
